### ISSUE TITLE
不能单独下载一个网页的md文件吗

### ISSUE THREAD

**Issue by yoro99** [TonyChenn/BlogExportTool#1]
请问这个程序不能单独下载单独网页的md文件吗？一定要通过个人主页下载吗？

**Comment by TonyChenn** [comment]
目前只能通过走主页进行下载。下次更新添加单个文档导出。

**Comment by yoro99** [comment]
> 目前只能通过走主页进行下载。下次更新添加单个文档导出。

不知道能不能对主页解析出的文件加一个搜索的功能，很不错的程序，期待更新😁

**Comment by TonyChenn** [comment]
建议挺好，有时间可以写下。

**Comment by whlttt** [comment]
一直提示token过期啊。

**Comment by TonyChenn** [comment]
> 一直提示token过期啊。

你好，里面有个接口过期了，还没来得及修复。

**Comment by whlttt** [comment]
> > 一直提示token过期啊。
> 
> 你好，里面有个接口过期了，还没来得及修复。

那就是现在这个工具暂时不能用吧？好的，谢谢了。
