### ISSUE TITLE
最新Token总提示过期

### ISSUE THREAD

**Issue by tianjiaoshanzai** [TonyChenn/BlogExportTool#2]
重新登陆再更新Token无效

**Comment by TonyChenn** [comment]
没有重现你的问题，确认下是不是UuserName和Token填错了。

**Comment by joeqi** [comment]
我也遇到了同样的问题，提示token过期。
我看dat文件里
UserName :username
UserToken :0500e2229f544a00994bf77125e79cf4
冒号前后要不要空格？

**Comment by TonyChenn** [comment]
加不加空格都行，但是软件现在用不了，csdn接口过期了，没有时间维护。

---原始邮件---
发件人: "Yuwei Qi"<notifications@github.com&gt;
发送时间: 2019年12月20日(周五) 下午3:41
收件人: "TonyChenn/BlogExportTool"<BlogExportTool@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"TonyChenn"<852454151@qq.com&gt;;
主题: Re: [TonyChenn/BlogExportTool] 最新Token总提示过期 (#2)



我也遇到了同样的问题，提示token过期。
 我看dat文件里
 UserName :username
 UserToken :0500e2229f544a00994bf77125e79cf4
 冒号前后要不要空格？
