### ISSUE TITLE
csdn_config.dat这个文件在repo中存在吗？

### ISSUE THREAD

**Issue by AChaoZJU** [TonyChenn/BlogExportTool#5]
没有搜索到这个csdn_config.data
如果没有，我需要把这个文件创建在哪个目录下？
谢谢！

**Comment by TonyChenn** [comment]
> 没有搜索到这个csdn_config.data
> 
> 如果没有，我需要把这个文件创建在哪个目录下？
> 
> 谢谢！

自动生成的
